name: Bundle Stats

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false

      - name: Get Node.js version from package.json
        id: node-version
        run: |
          NODE_VERSION=$(node -p "require('./package.json').engines.node.replace('>=', '')")
          echo "version=$NODE_VERSION" >> $GITHUB_OUTPUT

      - name: Compare bundle stats
        uses: grafana/plugin-actions/bundle-size@4698961fa64137fcac207108397ebe8a738a33d1 # main
        with:
          node-version: ${{ steps.node-version.outputs.version }}
