name: create bundle stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Run once per day at midnight UTC
  push:
    branches:
      - main

permissions:
  contents: 'read'
  actions: 'write'

jobs:
  build-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false

      - name: Get Node.js version from package.json
        id: node-version
        run: |
          NODE_VERSION=$(node -p "require('./package.json').engines.node.replace('>=', '')")
          echo "version=$NODE_VERSION" >> $GITHUB_OUTPUT

      - name: Install pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8

      - name: Setup Node.js environment
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ steps.node-version.outputs.version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build frontend
        run: pnpm run build --profile --json stats.json

      - name: Upload stats.json artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: main-branch-stats
          path: stats.json
          retention-days: 90
          overwrite: true
